---
# tasks to install and configure Logstash for Ubuntu and CentOS

- name: Install dependencies for Ubuntu
  ansible.builtin.package:
    name:
      - apt-transport-https
      - default-jre
      - gpg
  when: ansible_distribution == "Ubuntu"
  retries: 2
  register: result
  until: result is succeeded
  tags: logstash

- name: Install dependencies for CentOS
  ansible.builtin.package:
    name:
      - java-1.8.0-openjdk
      - epel-release
      - gpg
  when: ansible_distribution == "CentOS"
  retries: 2
  register: result
  until: result is succeeded
  tags: logstash

- name: Add repository key for Ubuntu and CentOS
  ansible.builtin.apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
  retries: 2
  register: result
  until: result is succeeded
  tags: logstash

- name: Add Logstash repository for Ubuntu
  ansible.builtin.apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/{{ logstash_major_version }}.x/apt stable main'
  when: ansible_distribution == "Ubuntu"
  tags: logstash

- name: Add Logstash repository for CentOS
  ansible.builtin.yum_repository:
    name: elasticsearch
    description: Elasticsearch Repository
    baseurl: https://artifacts.elastic.co/packages/{{ logstash_major_version }}.x/yum
    gpgcheck: yes
    enabled: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
  when: ansible_distribution == "CentOS"
  tags: logstash

- name: Install Logstash on Ubuntu
  ansible.builtin.package:
    name:
      - logstash
  when: ansible_distribution == "Ubuntu"
  retries: 2
  register: result
  until: result is succeeded
  tags: logstash

- name: Install Logstash on CentOS
  ansible.builtin.package:
    name:
      - logstash
  when: ansible_distribution == "CentOS"
  retries: 2
  register: result
  until: result is succeeded
  tags: logstash

#- name: Copy general config file
#  ansible.builtin.copy:
#    content: '{{ logstash_full_config|to_yaml }}'
#    dest: /etc/logstash/logstash.yml
#    owner: root
#    group: root
#    mode: 0644
#  notify: restart logstash
#  tags: logstash

- name: Create patterns directory
  ansible.builtin.file:
    path: /etc/logstash/patterns
    owner: root
    group: root
    mode: 0755
    state: directory
  tags: logstash

#- name: Copy patterns files
#  ansible.builtin.copy:
#    content: '{{ item.value }}'
#    dest: '/etc/logstash/patterns/{{ item.key }}.conf'
#    owner: root
#    group: root
#    mode: 0644
#  loop: '{{ logstash_patterns|dict2items }}'
#  loop_control:
#    label: '{{ item.key }}'
#  tags: logstash

#- name: Copy input, output and filter files
#  ansible.builtin.template:
#    src: '{{ item }}.conf.j2'
#    dest: '/etc/logstash/conf.d/{{ item }}.conf'
#    owner: root
#    group: root
#    mode: 0644
#    validate: /usr/share/logstash/bin/logstash -t -f %s
#  loop:
#    - input
#    - output
#    - filter
#  notify: restart logstash
#  tags: logstash

#- name: Install plugins
#  community.general.logstash_plugin:
#    name: '{{ item.name }}'
#    state: '{{ item.state|default("present") }}'
#  loop: '{{ logstash_plugins }}'
#  tags: logstash

- name: Enable and start Logstash service
  ansible.builtin.service:
    name: logstash
    state: started
    enabled: true
  tags: logstash

- name: restart logstash
  ansible.builtin.service:
    name: logstash
    state: restarted

