---
- name: Install Kibana on Ubuntu
  apt:
    name: kibana
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Install Kibana on CentOS
  yum:
    name: kibana
    state: present
    update_cache: yes
  when: ansible_distribution == "CentOS"

- name: Start and enable Kibana
  service:
    name: kibana
    state: started
    enabled: yes
