
---
#- name: Add Elasticsearch GPG key for Ubuntu
#  apt_key:
#    url: "https://packages.elastic.co/GPG-KEY-elasticsearch"
#    state: present
#  when: ansible_distribution == 'Ubuntu'

#- name: Add Elasticsearch repository for Ubuntu
#  apt_repository:
#    repo: deb https://artifacts.elastic.co/packages/5.x/apt stable main
#    state: present
#  when: ansible_distribution == 'Ubuntu'

#- name: Install Elasticsearch for Ubuntu
#  apt:
#    name: elasticsearch
#    update_cache: yes
#    state: present
#  when: ansible_distribution == 'Ubuntu'


#- name: Update the config file to allow outside access
#  lineinfile:
#    dest: /etc/elasticsearch/elasticsearch.yml
#    regexp: '^network.host:'
#    line: 'network.host: 0.0.0.0'

#- name: Update the port in the config file
#  lineinfile:
#    dest: /etc/elasticsearch/elasticsearch.yml
#    regexp: '^http.port:'
#    line: 'http.port: 9200'

#- name: Start Elasticsearch
#  service:
#    name: elasticsearch
 #   state: started
 #   enabled: yes


















# tasks/main.yml

- name: Ensure Elasticsearch repository is added
  yum_repository:
    name: elasticsearch
    description: "Elasticsearch repository"
    baseurl: "{{ elasticsearch_repo_url }}"
    gpgcheck: yes
    gpgkey: "{{ elasticsearch_gpg_key }}"
  when: ansible_distribution == 'CentOS'

- name: Install Elasticsearch
  yum:
    name: "{{ elasticsearch_package_name }}"
    state: present

- name: Configure Elasticsearch
  template:
    src: elasticsearch.yml.j2
    dest: "{{ elasticsearch_config_path }}"
    owner: elasticsearch
    group: elasticsearch
    mode: '0644'
  notify: Restart Elasticsearch

- name: Ensure Elasticsearch service is enabled and started
  systemd:
    name: "{{ elasticsearch_service_name }}"
    enabled: yes
    state: started
